
export const db=()=>{const database=(env as unknown as {DB:D1Database}).DB;if(!database)throw new Error("Database unavailable");return database;};
export const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"no-store"}});
export const digest=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))).map(n=>n.toString(16).padStart(2,"0")).join("");
export async function hashPassword(password:string,salt:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations:100000,hash:"SHA-256"},key,256))).map(n=>n.toString(16).padStart(2,"0")).join("");}
export async function user(request:Request){const token=request.headers.get("cookie")?.match(/(?:^|;\s*)mg_session=([^;]+)/)?.[1];if(!token)return null;return db().prepare("SELECT users.id, users.email, users.name, users.demo FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires>?").bind(await digest(token),Date.now()).first<{id:string,email:string|null,name:string,demo:number}>();}
export function sameOrigin(request:Request){const origin=request.headers.get("origin");return !origin||origin===new URL(request.url).origin;}
export async function session(request:Request,id:string){const token=crypto.randomUUID()+crypto.randomUUID();await db().prepare("INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)").bind(await digest(token),id,Date.now()+7*86400000).run();return `mg_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${new URL(request.url).protocol==="https:"?"; Secure":""}`;}
export async function throttle(key:string,limit=10){const now=Date.now();await db().prepare("INSERT INTO attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END, until=CASE WHEN until<? THEN excluded.until ELSE until END").bind(key,now+15*60000,now,now).run();const row=await db().prepare("SELECT count FROM attempts WHERE key=?").bind(key).first<{count:number}>();return (row?.count||0)>limit;}
export async function readJson(request:Request):Promise<Record<string,unknown>>{const text=await request.text();if(text.length>16384)throw new Error('INVALID_INPUT');try{const data=JSON.parse(text);if(!data||Array.isArray(data)||typeof data!=='object')throw new Error('invalid');return data;}catch{throw new Error('INVALID_INPUT');}}
